# Generated by Django 4.1 on 2022-08-28 16:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_project_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, default=django.contrib.auth.models.User, null=True, related_name='allowed_project_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
